### ISSUE TITLE
How do you import built web components?

### ISSUE THREAD

**Issue by Vulwsztyn** [bmomberger-bitovi/web-components-example#1]
Hi,
sorry for making this an issue, but I'm seeing recent activity here and this looks exactly how my use case.
Once you have your web components in the `public` dir how do you include them in the html file?

I tried
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script src="nav-links.umd.js"></script>
    <nav-links></nav-links>
  </body>
</html>
```
But the wc is not getting rendered.

**Comment by bmomberger-bitovi** [comment]
I can't comment on your particular HTML file because I don't know where it's hosted or how it's being served, and whether it's a sibling to nav-links.umd.js.  What I can do is direct you to [the consumer app](/bmomberger-bitovi/web-components-consumer) to see how it would be imported and used in a next.js app.  Each published Web component is wrapped by a wrapper React component in wrappers/

**Comment by Vulwsztyn** [comment]
Sorry for not clarifying that:
yes, it's a sibling to nav-links.umd.js. I created it in the `public` dir and put the content from the previous comment there.

I'm serving it with `browser-sync` with `browser-sync start --server --directory --files "**/*"`

I'll have a look at the consumer app. Thank you for the time put into replying to me.

**Comment by tombohub** [comment]
@Vulwsztyn how did you create `nav-links.umd.js` file?
